development:
  adapter: postgresql
  encoding: unicode
  database: jcd_dev
  pool: 5
  host: localhost
  port: 5432  
   

test:
  adapter: postgresql
  encoding: unicode
  database: jcd_test
  pool: 5
  host: localhost
  port: 5432  
